export const samplePrompt = [
  "Create a luxury perfume advertisement.",
  "Keep the bottle centered, the headline at the top, the logo in the upper-left corner,",
  "and a limited-drop badge near the lower-right side of the product.",
  "Use warm ivory lighting, polished glass reflections, and an editorial premium style.",
].join(" ");

export const sampleLayout = {
  version: "0.1.0",
  canvas: {
    width: 1080,
    height: 1350,
    unit: "px",
    background: {
      type: "solid",
      color: "#f6efe5",
    },
  },
  assets: [],
  objects: [
    {
      id: "background",
      name: "Background",
      type: "rectangle",
      x: 0,
      y: 0,
      width: 1080,
      height: 1350,
      rotation: 0,
      opacity: 1,
      zIndex: 0,
      role: "background",
      fill: {
        type: "linear-gradient",
        from: "#fff8ed",
        to: "#ead7c2",
      },
    },
    {
      id: "logo",
      name: "Brand Logo",
      type: "logo",
      x: 78,
      y: 64,
      width: 178,
      height: 62,
      rotation: 0,
      opacity: 1,
      zIndex: 10,
      role: "logo",
      content: "MAISON LUNE",
    },
    {
      id: "headline",
      name: "Headline",
      type: "text",
      x: 90,
      y: 150,
      width: 900,
      height: 150,
      rotation: 0,
      opacity: 1,
      zIndex: 20,
      role: "headline",
      content: "NEW ELEGANCE",
      fontFamily: "Georgia, 'Times New Roman', serif",
      fontSize: 86,
      fontWeight: 700,
      color: "#191613",
      align: "center",
      lineHeight: 1.02,
    },
    {
      id: "subtitle",
      name: "Subtitle",
      type: "text",
      x: 190,
      y: 300,
      width: 700,
      height: 74,
      rotation: 0,
      opacity: 0.86,
      zIndex: 21,
      role: "subtitle",
      content: "A luminous fragrance composed for quiet confidence.",
      fontFamily: "Inter, Arial, sans-serif",
      fontSize: 30,
      fontWeight: 400,
      color: "#54473c",
      align: "center",
      lineHeight: 1.2,
    },
    {
      id: "product-halo",
      name: "Product Halo",
      type: "circle",
      x: 252,
      y: 428,
      width: 576,
      height: 576,
      rotation: 0,
      opacity: 0.58,
      zIndex: 25,
      role: "decoration",
      fill: {
        type: "radial-gradient",
        inner: "rgba(255,255,255,0.96)",
        outer: "rgba(229,203,172,0.18)",
      },
    },
    {
      id: "product",
      name: "Perfume Bottle",
      type: "product-image",
      x: 334,
      y: 440,
      width: 412,
      height: 620,
      rotation: 0,
      opacity: 1,
      zIndex: 30,
      role: "product",
      fit: "contain",
      content: "PERFUME",
    },
    {
      id: "promo-badge",
      name: "Promo Badge",
      type: "badge",
      x: 718,
      y: 915,
      width: 236,
      height: 102,
      rotation: -5,
      opacity: 1,
      zIndex: 40,
      role: "promo-badge",
      content: "LIMITED DROP",
      fill: {
        type: "solid",
        color: "#1d1813",
      },
    },
    {
      id: "footer",
      name: "Footer",
      type: "text",
      x: 150,
      y: 1170,
      width: 780,
      height: 80,
      rotation: 0,
      opacity: 0.82,
      zIndex: 45,
      role: "footer",
      content: "Available this season only",
      fontFamily: "Inter, Arial, sans-serif",
      fontSize: 34,
      fontWeight: 500,
      color: "#382e27",
      align: "center",
      lineHeight: 1.15,
    },
  ],
  guides: [
    {
      axis: "x",
      position: 540,
    },
  ],
  meta: {
    title: "Luxury Perfume Ad",
  },
};
